name: Main CI/CD Pipeline

on:
  pull_request:
    branches: 
      - main
    types: 
      - closed
    paths:
      - 'cat-api-node/**'
      - 'cat-api-py/**'
      - '.github/workflows/**'

  push:
    branches:
      - develop
      - 'release/*' 
      - 'hotfix/*'
    paths:
      - 'cat-api-node/**'
      - 'cat-api-py/**'
      - '.github/workflows/**'

jobs:
  node-app:
    uses: ./.github/workflows/core.yml
    secrets: inherit # this is required to pass the secrets
    with:
      directory: cat-api-node
      image: cat-api/node
      lang: node
      version: 24
      command_install: npm ci
      command_test: npm run test

  python-app:
    uses: ./.github/workflows/core.yml
    secrets: inherit
    with:
      directory: cat-api-py
      image: cat-api/py
      lang: python
      version: 3.12
      command_install: pip install -r requirements.txt
      command_test: python -m pytest test_app.py
